version: "3.7"
services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      WATCHER_BASE_PATH: "/app/exercises"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: "kt ts tsx"
      IGNORE_DIRS: ".git"
    volumes:
      - "./stock_management_server:/app/exercises/stock_management_server"
      - "./stock_management_client:/app/exercises/stock_management_client"
      - "./attendance_id:/app/sync/attendance_id"
    tty: true
    stdin_open: true
  stock-management-server:
    image: "ghcr.io/skiller-whale/rest-api-design-in-kotlin/introduction-to-rest-apis/stock-management-server"
    build:
      context: "./stock_management_server"
    ports:
      - "7070:7070"
    volumes:
      - "./stock_management_server/src:/app/src"
  stock-management-client:
    image: "ghcr.io/skiller-whale/rest-api-design-in-kotlin/introduction-to-rest-apis/stock-management-client"
    build:
      context: "./stock_management_client"
    ports:
      - "7071:7071"
    volumes:
      - "./stock_management_client/src:/src"
