version: "3.7"
services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync:dockerize"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      WATCHER_BASE_PATH: "/app/exercises"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: "kt ts tsx"
      IGNORE_DIRS: ".git"
    volumes:
      - "./stock_management_server_1/src/main/kotlin/stock_management:/app/exercises/stock_management_server_1"
      - "./stock_management_client_1/src:/app/exercises/stock_management_client_1"
      - "./stock_management_server_2/src/main/kotlin/stock_management:/app/exercises/stock_management_server_2"
      - "./stock_management_client_2/src:/app/exercises/stock_management_client_2"
      - "./attendance_id:/app/sync/attendance_id"
    tty: true
    stdin_open: true
  stock_management_server_1:
    build:
      context: "./stock_management_server_1"
    ports:
      - "7070:7070"
    volumes:
      - "./stock_management_server_1/src:/app/src"
  stock_management_client_1:
    build:
      context: "./stock_management_client_1"
    ports:
      - "7071:7071"
    volumes:
      - "./stock_management_client_1/src:/src"
  stock_management_server_2:
    build:
      context: "./stock_management_server_2"
    ports:
      - "7072:7072"
    volumes:
      - "./stock_management_server_2/src:/app/src"
  stock_management_client_2:
    build:
      context: "./stock_management_client_2"
    ports:
      - "7073:7073"
    volumes:
      - "./stock_management_client_2/src:/src"
