version: "3.7"
services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync:0.2.1"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/app/exercises"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: .kt
      IGNORE_DIRS: ".git"
    volumes:
      - "./stock_management_server/src/main/kotlin/stock_management:/app/exercises/stock_management_server"
      - "./attendance_id:/app/sync/attendance_id"
    tty: true
    stdin_open: true
  dev-server:
    image: "ghcr.io/skiller-whale/rest-api-design-in-kotlin/introduction-to-apis/stock-management-server"
    build:
      context: "./stock_management_server"
    ports:
      - "7070:7070"
    volumes:
      - "./stock_management_server/src:/app/src"
