version: '3.7'
services:
  sync:
    image: ghcr.io/skiller-whale/learnersync:dockerize
    network_mode: host
    environment:
      SERVER_URL: https://train.skillerwhale.com/
      WATCHER_BASE_PATH: /app/exercises
      ATTENDANCE_ID_FILE: /app/sync/attendance_id
      WATCHED_EXTS: kt
      IGNORE_DIRS: .git
    volumes:
      - ./src:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
    tty: true
    stdin_open: true
  dev-server:
    build:
      context: .
    ports:
      - "7070:7070"
    volumes:
      - ./src:/app/src
