version: "3.7"
services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync:0.2.1"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/app/exercises"
      ATTENDANCE_ID_FILE: "/app/attendance_id"
      WATCHED_EXTS: .kt .log
      IGNORE_DIRS: ".git"
    volumes:
      - "./http:/app/exercises/http"
      - "./stock_management_server:/app/exercises/stock_management_server"
      - "../attendance_id:/app/attendance_id"
    tty: true
    stdin_open: true
  stock-management-server:
    image: "ghcr.io/skiller-whale/rest-api-design-in-kotlin/request-design/stock-management-server"
    build:
      context: "./stock_management_server"
    ports:
      - "7070:7070"
    volumes:
      - "./stock_management_server/src:/app/src"
  httpie:
    image: "ghcr.io/skiller-whale/rest-api-design-in-kotlin/request-design/http"
    build:
      context: "./http"
    profiles: ["httpie"]
    volumes:
      - "./http/logs:/logs"
      - ".:/app"
