version: '3.7'
services:
  sync:
    image: ghcr.io/skiller-whale/learnersync:dockerize
    network_mode: host
    environment:
      SERVER_URL: https://train.skillerwhale.com/
      WATCHER_BASE_PATH: /app/exercises
      ATTENDANCE_ID_FILE: /app/attendance_id
      WATCHED_EXTS: kt log
      IGNORE_DIRS: .git
    volumes:
      - ./src:/app/exercises
      - ./attendance_id:/app/attendance_id
    tty: true
    stdin_open: true
  dev-server:
    image: ghcr.io/skiller-whale/rest-api-design-in-kotlin/request-design
    ports:
      - "7070:7070"
    volumes:
      - ./src:/app/src
  httpie:
    image: alpine/httpie
    profiles: ["httpie"]
    volumes:
      - ./http/:/app/http
    entrypoint: >
      su -s /bin/sh -c 'exec /app/http/sh' root
    volumes:
      - .:/app
