### CREATE
POST http://localhost:7070/warehouses HTTP/1.1
Content-Type: application/json

{
    "name": "Jupiter"
}

# READ

### Get all.
GET http://localhost:7070/warehouses HTTP/1.1


### Get one
GET http://localhost:7070/warehouses/1 HTTP/1.1

### Get one - Not found.
GET http://localhost:7070/warehouses/20 HTTP/1.1

# UPDATE

### Update existing (Doesn't deal with id mismatches.)
PUT http://localhost:7070/warehouses/0 HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Apollo"
}

### Update new (Should fail)
PUT http://localhost:7070/warehouses/25 HTTP/1.1
Content-Type: application/json

{
    "id": 25,
    "name": "Apollo"
}

# DELETE
### Delete existing
DELETE http://localhost:7070/warehouses/3 HTTP/1.1

### Not found.
DELETE http://localhost:7070/warehouses/25 HTTP/1.1
